name: flutter_application_1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.2
  mime: ^1.0.0
  http: ^1.3.0
  flutter_sound: ^9.23.1
  permission_handler: ^10.0.0
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.10
  dcdg: ^4.1.0
  convert: ^3.0.1
  flutter_svg: ^2.0.17
  #firebase_auth: ^4.17.8
  kakao_flutter_sdk: ^1.9.1+2
  kakao_flutter_sdk_user: ^1.2.1
  flutter_secure_storage: ^5.0.1
  shared_preferences: ^2.0.6
  dio: ^5.0.0
  flutter_cache_manager: ^3.3.0
  archive: ^3.3.4
  sign_in_with_apple: ^5.0.0
  simple_circular_progress_bar: ^1.0.2
  animated_bottom_navigation_bar: ^1.3.3
  card_swiper: ^3.0.1
  table_calendar: ^3.1.2
  intl: ^0.19.0
  timeago: ^3.7.0
  dropdown_button2: ^2.3.9
  flutter_bounce: ^1.1.0
  app_tutorial: ^1.0.6
  dotted_decoration: ^2.0.0
  #flutter_launcher_icons: ^0.12.0
  fl_chart: ^0.69.0
  google_sign_in: ^6.2.1
  # audio 관련 package
  just_audio: ^0.9.40
  audioplayers: ^6.1.0
  audio_session: ^0.1.25
  flutter_blue_plus: ^1.33.4
  flutter_screenutil: ^5.9.3
  auto_size_text: ^3.0.0
  simple_ripple_animation: ^0.1.0
  glowy_borders: ^1.0.2
  firebase_core: ^3.4.0
  firebase_messaging: ^15.2.2
  cloud_firestore: ^5.6.3
  googleapis_auth: ^1.6.0
  flutter_local_notifications: ^18.0.1
  dart_jsonwebtoken: ^2.17.0
  firebase_analytics: ^11.4.4
  audio_waveforms: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

  #flutter_launcher_icons: "^0.12.0"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  iamge_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/image/
    - assets/tutorial/
    - assets/data/
    - assets/image/home_character/
    - assets/image/dialog_character/
    - assets/image/feedback_stamp/
  fonts:
    - family: BM_Jua
      fonts:
        - asset: assets/font/BMJua.otf

    - family: Marine
      fonts:
        - asset: assets/font/Marine-Black.ttf
        - asset: assets/font/Marine-Bold.ttf
        - asset: assets/font/Marine-Light.ttf
        - asset: assets/font/Marine-Regular.ttf

    - family: MADE-Tommy-Soft
      fonts:
        - asset: assets/font/MADE-Tommy-Soft-Thin.otf
          weight: 100
        - asset: assets/font/MADE-Tommy-Soft-Light.otf
          weight: 300
        - asset: assets/font/MADE-Tommy-Soft-Regular.otf
          weight: 400
        - asset: assets/font/MADE-Tommy-Soft-Medium.otf
          weight: 500
        - asset: assets/font/MADE-Tommy-Soft-Bold.otf
          weight: 700
        - asset: assets/font/MADE-Tommy-Soft-ExtraBold.otf
          weight: 800
        - asset: assets/font/MADE-Tommy-Soft-Black.otf
          weight: 900

    - family: Pretendard
      fonts:
        - asset: assets/font/Pretendard-Thin.otf
          weight: 100
        - asset: assets/font/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/font/Pretendard-Light.otf
          weight: 300
        - asset: assets/font/Pretendard-Regular.otf
          weight: 400
        - asset: assets/font/Pretendard-Medium.otf
          weight: 500
        - asset: assets/font/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/font/Pretendard-Bold.otf
          weight: 700
        - asset: assets/font/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/font/Pretendard-Black.otf
          weight: 900

    - family: CustomIcons
      fonts:
        - asset: assets/icon/CustomIcons.ttf
    - family: LoginIcons
      fonts:
        - asset: assets/icon/LoginIcons.ttf
